### ISSUE TITLE
Unable to connect to proxy server

### ISSUE THREAD

**Issue by madhurinagare** [xcist/documentation#1]
I tried installing PyCharm and setting HTTP Proxy as per the documentation.
However, when I click on check connection with  http://www.google.com, it shows an error. Problem with connection: proxy.research.ge.com. 
Also, because of this I am not able to install additional packages.
I have restarted the PyCharm and even PC after changing the proxy settings.
If I click auto-detect proxy settings, then everything works fine.
I am working on mac OS.
Are these proxy settings specific to GE environment or do I have to do additional settings?

**Comment by MingyeWu** [comment]
Hi Madhuri,
The proxy setting should be per your internet environment.
One more thing, CatSim doesn't support Mac OS yet. We suggest to run CatSim on Linux 64-bit system.

**Comment by madhurinagare** [comment]
Thanks Mingye for the reply.
I could run the simulation on a Linux system.
I think the documentation is more focussed on windows systems. I have made my own notes for the linux system installation.
If you want, I can forward them to you to add to the documentation.

I have further questions. I might have got these questions because I have never worked with the raw data or catsim MATLAB before.
1. There is one sample phantom CatSim_logo.json. It is a very small phantom. Are phantoms for human body included in the catsim? Where can I find them?
2. Does .prep file contain sinogram data? If so, how and where can we get reconstructed images?
3. Is it possible in current version to include a material in human body phantom? If so, is it possible for you to give a brief demo code?
4. I see CatSim_logo.density_1 and CatSim_logo.density_2 files in data/phantom. What is the function of  these files? how to use them?

Sorry for lot of questions.
Thank you.



On Sep 18, 2020, at 1:27 PM, Mingye Wu <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Madhuri,
The proxy setting should be per your internet environment.
One more thing, CatSim doesn't support Mac OS yet. We suggest to run CatSim on Linux 64-bit system.

**Comment by MingyeWu** [comment]
For your questions:
1. Currently there's only one sample phantom. More phantoms are in progress.

2. Yes, *.prep is the raw data after -log process (sino gram). The reconstruction algorithm is not included yet. The current version is a minimum version that can generate sino gram.
air, offset, and scan are CT acquisitions:
*.air is air scan, i.e. X-ray on, no phantom;
*.offset is offset scan, i.e. X-ray off;
*.scan is the phantom scan, i.e. X-ray on, with phantom;
*.prep is the raw data after -log.

3 and 4: Current version supports voxelized phantom.
Each voxelized phantom has two kinds of files: a .json file and binary file(s). In this sample:
The .json code defines the size/shape of the phantom, and specifies the files of material density volume.
The .density_xx is binary data that defines the densities of all the voxels. The dimension and data type are defined in .json file. They are the input of the projector in CatSim.
Voxelized phantom can be generated from clinical CT images. You will need to identify the materials in the image, convert it into density volume, and follow the structure to generate the .json file. The binary files are usually float32.


There will be an update soon, with voxelized tumor phantoms.

I'm closing this issue, since it's about two irrelevant questions. 
Thank you for the questions!

**Comment by madhurinagare** [comment]
> For your questions:
> 
> 1. Currently there's only one sample phantom. More phantoms are in progress.
> 2. Yes, *.prep is the raw data after -log process (sino gram). The reconstruction algorithm is not included yet. The current version is a minimum version that can generate sino gram.
>    air, offset, and scan are CT acquisitions:
>    *.air is air scan, i.e. X-ray on, no phantom;
>    *.offset is offset scan, i.e. X-ray off;
>    *.scan is the phantom scan, i.e. X-ray on, with phantom;
>    *.prep is the raw data after -log.
> 
> 3 and 4: Current version supports voxelized phantom.
> The .json code defines the size/shape of the phantom, and specifies the files of material density volume.
> The .density_xx is binary data that defines the densities of all the voxels. The dimension and data type are defined in .vp file. They are the input of the projector in CatSim.
> Voxelized phantom can be generated from clinical CT images. You will need to identify the materials in the image, convert it into density volume, and follow the format generate the .json file and the binary files.
> 
> There will be an update soon, with voxelized tumor phantoms.
> 
> I'm closing this issue, since it's about two irrelevant questions.
> Thank you for the questions!

Okay. thanks.
